[site]
name = "NekoCAS"
port = 8000
icp = ""
security_key = ""
csrf_key = ""

[mysql]
user = ""
password = ""
addr = "tcp(localhost:3306)"
name = ""

[redis]
addr = "127.0.0.1:6379"
password = ""

[mail]
account = ""
password = ""
smtp = ""
port = 465

[ldap]
enabled = false
url= "ldap://127.0.0.1"
bind_dn = "cn=readonly,dc=example,dc=com"
bind_password = "password"
user_filter = "(email=%s)"
base_dn = "dc=example,dc=com"
sync_interval = "24h"

[ldap.mapping]
nickname = "cn"
email = "mail"
avatar = "avatar"
